"""Native global-plan drafting in a run-owned, revision-bound workspace."""

from __future__ import annotations

import json

import flynn_agents_sdk as flynn
from jsonschema import Draft202012Validator

from vfx_harness.agents.planning_workspace import PlanningWorkspace
from vfx_harness.observability import prepared_publication
from vfx_harness.orchestration import plan_authoring
from vfx_harness.orchestration.plan_bundle_integrity import digest

MAX_MAPPING_BYTES = 64_000


def ownership_mapping_publication(
    binding: PlanningWorkspace,
) -> flynn.Tool:
    """Bind the sole model-authored mapping to an already prepared workspace.

    The caller holds the run's owner fence and supplies its live-attempt check.
    Successful expansion is a draft observation, never gate or publication authority.
    A failed write remains unresolved in Flynn; the caller must discard or explicitly
    reconcile that workspace rather than repeat the operation automatically.
    """
    layout = binding.layout
    workspace = binding.root
    registry = plan_authoring.clause_registry(workspace / "brief.md")
    schema = plan_authoring.ownership_mapping_authoring_schema()
    validator = Draft202012Validator(schema)

    def validate(arguments):
        errors = [error.message for error in validator.iter_errors(arguments)]
        if errors:
            raise ValueError("ownership mapping schema: " + "; ".join(errors))
        if len(json.dumps(arguments, ensure_ascii=False).encode("utf-8")) > MAX_MAPPING_BYTES:
            raise ValueError(f"ownership mapping exceeds {MAX_MAPPING_BYTES} bytes; reduce the global draft")
        errors = plan_authoring.validate_mapping(arguments, registry, workspace / "refs")
        if errors:
            raise ValueError("ownership mapping is invalid: " + "; ".join(errors))

    async def publish(arguments):
        binding.check()
        payload = (json.dumps(arguments, indent=1, ensure_ascii=False) + "\n").encode("utf-8")

        def replace_mapping(current):
            observed = digest(current) if current is not None else None
            if observed != binding.owned["ownership_mapping.json"]:
                raise ValueError("ownership mapping changed before publication; preserve the newer draft")
            return payload, None

        prepared_publication.publish_file_update(
            layout.shot, workspace / "ownership_mapping.json", replace_mapping,
            authority_binding=f"native-mapping:{layout.run_id}:{digest(binding.marker_bytes)}",
        )
        written = plan_authoring.expand_mapping(workspace, arguments)
        if set(written) != set(plan_authoring.MAPPING_ARTIFACTS):
            raise ValueError("mapping expansion did not produce its complete declared artifact set")
        # Independently reopen all generated bytes; retain exact identities across
        # any next inference so another writer's revision cannot be overwritten.
        binding.owned = binding.outputs()
        if any(value is None for value in binding.owned.values()):
            raise ValueError("mapping expansion left missing artifacts; discard or reconcile the incomplete draft")
        binding.check_inputs()
        return flynn.ToolResult(
            content=(flynn.TextContent(
                "Global draft expanded. Deterministic gate and authority publication remain due."
            ),),
            data_json=json.dumps({
                "schema": "vfx-harness.mapping-observation/v1",
                **binding.identity(), "gate_attested": False,
            }, sort_keys=True),
        )

    return flynn.Tool.structured(
        "publish_ownership_mapping",
        description=("Submit the complete ownership/DAG mapping, at most 64000 UTF-8 JSON bytes. "
                     "The harness validates and expands the draft in its bound workspace. "
                     "No path argument; this does not gate or publish selected authority."),
        parameters_json=json.dumps(schema), validate=validate, execute=publish, external_action=True,
    )
